### ISSUE TITLE
Missing deps on a RP3

### ISSUE THREAD

**Issue by manekinekko** [pimoroni/pidi-spotify#10]
The setup will fail because of some missing dependencies on a raspberry pi 3.

Here are some of the error logs (for the reference):

```
Failed building wheel for Pillow
...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 154, in save_modules
    yield saved
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 195, in setup_context
    yield
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 250, in run_setup
    _execfile(setup_script, ns)
  File "/usr/lib/python3/dist-packages/setuptools/sandbox.py", line 45, in _execfile
    exec(code, globals, locals)
  File "/tmp/easy_install-lhbguwjl/Pillow-8.0.1/setup.py", line 914, in <module>
__main__.RequiredDependencyException:

The headers or library files could not be found for jpeg,
a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html
```

and...

```
src/_imagingtk.c:16:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
compilation terminated.
src/_imagingft.c:22:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
compilation terminated.
src/_imaging.c:75:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
src/_imagingmath.c:16:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
compilation terminated.
compilation terminated.
src/_imagingmorph.c:14:10: fatal error: Python.h: No such file or directory
 #include "Python.h"
          ^~~~~~~~~~
compilation terminated.
error: Setup script exited with error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1
```

Installing the following deps solved the issue:
```
sudo apt-get install python3-setuptools python3-dev libjpeg-dev
```

I opened an PR #9 to fix these issues.

**Comment by thirdr** [comment]
Closed as resolved
