### ISSUE TITLE
fifo os.mkfifo(fifo_name) FileExistsError?

### ISSUE THREAD

**Issue by treatmesubj** [pimoroni/pidi-spotify#16]
Hey there, I think I ran `pidi_spotify` and `ctrl + C`'d it pretty quick and now I'm getting this error:
```
pi@raspberrypi:~ $ pidi_spotify
Traceback (most recent call last):
  File "/usr/local/bin/pidi_spotify", line 11, in <module>
    load_entry_point('pidi-spotify==0.0.1', 'console_scripts', 'pidi_spotify')()
  File "/usr/local/lib/python3.7/dist-packages/pidi_spotify-0.0.1-py3.7.egg/pidi_spotify/__init__.py", line 164, in main
  File "/usr/local/lib/python3.7/dist-packages/pidi_spotify-0.0.1-py3.7.egg/pidi_spotify/fifo.py", line 13, in __init__
FileExistsError: [Errno 17] File exists
```

I've never messed around with a Python egg and the fifo stuff is over my head, but is there a way to figure out where the fifo file is and maybe just delete it?

Thanks

**Comment by treatmesubj** [comment]
nvm. a simple reboot of my pi resolved it I guess.
