### ISSUE TITLE
On event exit code 1

### ISSUE THREAD

**Issue by impulsio** [pimoroni/pidi-spotify#20]
Hello,

Raspotify is working perfectly on my Pi Zero 2W but pidi_spotify doesn't seems to handle the hook call

I get this message :

`Oct 07 09:05:43 raspberrypi librespot[1618]: [2024-10-07T07:05:43Z WARN  librespot::player_event_handler] On event program pidi_spotify --hook returned exit code 1
`

I'm on debian 11

Does anyone have the same issue ?

Sincerely

**Comment by impulsio** [comment]
I get this log with different config

```
Oct 07 18:16:21 raspberrypi librespot[1823]: Traceback (most recent call last):
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/lib/python3.9/dist-packages/numpy/_core/__init__.py", line 23, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:     from . import multiarray
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/lib/python3.9/dist-packages/numpy/_core/multiarray.py", line 10, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:     from . import overrides
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/lib/python3.9/dist-packages/numpy/_core/overrides.py", line 8, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:     from numpy._core._multiarray_umath import (
Oct 07 18:16:21 raspberrypi librespot[1823]: ImportError: libopenblas.so.0: cannot enable executable stack as shared object requires: Operation not permitted
Oct 07 18:16:21 raspberrypi librespot[1823]: During handling of the above exception, another exception occurred:
Oct 07 18:16:21 raspberrypi librespot[1823]: Traceback (most recent call last):
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/lib/python3.9/dist-packages/numpy/__init__.py", line 114, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:     from numpy.__config__ import show as show_config
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/lib/python3.9/dist-packages/numpy/__config__.py", line 4, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:     from numpy._core._multiarray_umath import (
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/lib/python3.9/dist-packages/numpy/_core/__init__.py", line 49, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:     raise ImportError(msg)
Oct 07 18:16:21 raspberrypi librespot[1823]: ImportError:
Oct 07 18:16:21 raspberrypi librespot[1823]: IMPORTANT: PLEASE READ THIS FOR ADVICE ON HOW TO SOLVE THIS ISSUE!
Oct 07 18:16:21 raspberrypi librespot[1823]: Importing the numpy C-extensions failed. This error can happen for
Oct 07 18:16:21 raspberrypi librespot[1823]: many reasons, often due to issues with your setup or how NumPy was
Oct 07 18:16:21 raspberrypi librespot[1823]: installed.
Oct 07 18:16:21 raspberrypi librespot[1823]: We have compiled some common reasons and troubleshooting tips at:
Oct 07 18:16:21 raspberrypi librespot[1823]:     https://numpy.org/devdocs/user/troubleshooting-importerror.html
Oct 07 18:16:21 raspberrypi librespot[1823]: Please note and check the following:
Oct 07 18:16:21 raspberrypi librespot[1823]:   * The Python version is: Python3.9 from "/usr/bin/python3"
Oct 07 18:16:21 raspberrypi librespot[1823]:   * The NumPy version is: "2.0.2"
Oct 07 18:16:21 raspberrypi librespot[1823]: and make sure that they are the versions you expect.
Oct 07 18:16:21 raspberrypi librespot[1823]: Please carefully study the documentation linked above for further help.
Oct 07 18:16:21 raspberrypi librespot[1823]: Original error was: libopenblas.so.0: cannot enable executable stack as shared object requires: Operation not permitted
Oct 07 18:16:21 raspberrypi librespot[1823]: The above exception was the direct cause of the following exception:
Oct 07 18:16:21 raspberrypi librespot[1823]: Traceback (most recent call last):
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/bin/pidi_spotify", line 33, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:     sys.exit(load_entry_point('pidi-spotify==0.0.1', 'console_scripts', 'pidi_spotify')())
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/bin/pidi_spotify", line 25, in importlib_load_entry_point
Oct 07 18:16:21 raspberrypi librespot[1823]:     return next(matches).load()
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/lib/python3.9/importlib/metadata.py", line 77, in load
Oct 07 18:16:21 raspberrypi librespot[1823]:     module = import_module(match.group('module'))
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/lib/python3.9/importlib/__init__.py", line 127, in import_module
Oct 07 18:16:21 raspberrypi librespot[1823]:     return _bootstrap._gcd_import(name[level:], package, level)
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "<frozen importlib._bootstrap>", line 664, in _load_unlocked
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "<frozen importlib._bootstrap>", line 627, in _load_backward_compatible
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "<frozen zipimport>", line 259, in load_module
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/lib/python3.9/dist-packages/pidi_spotify-0.0.1-py3.9.egg/pidi_spotify/__init__.py", line 15, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "<frozen zipimport>", line 259, in load_module
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/lib/python3.9/dist-packages/pidi_spotify-0.0.1-py3.9.egg/pidi_spotify/st7789.py", line 6, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/lib/python3.9/dist-packages/pidi_display_st7789-0.1.2-py3.9.egg/pidi_display_st7789/__init__.py", line 2, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:     from ST7789 import ST7789 as ST7789, BG_SPI_CS_FRONT, ST7789_DISPOFF, ST7789_DISPON
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/lib/python3.9/dist-packages/st7789-1.0.1-py3.9.egg/ST7789.py", line 3, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:     from st7789 import *  # noqa F403
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/lib/python3.9/dist-packages/st7789-1.0.1-py3.9.egg/st7789/__init__.py", line 26, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:     import numpy
Oct 07 18:16:21 raspberrypi librespot[1823]:   File "/usr/local/lib/python3.9/dist-packages/numpy/__init__.py", line 119, in <module>
Oct 07 18:16:21 raspberrypi librespot[1823]:     raise ImportError(msg) from e
Oct 07 18:16:21 raspberrypi librespot[1823]: ImportError: Error importing numpy: you should not try to import numpy from
Oct 07 18:16:21 raspberrypi librespot[1823]:         its source directory; please exit the numpy source tree, and relaunch
Oct 07 18:16:21 raspberrypi librespot[1823]:         your python interpreter from there.
```


even when I launch the below command on root or raspotify user :
`TRACK_ID="0PITyfwD0Vlp5IzQXnIrkB" PLAYER_EVENT="playing" pidi_spotify --hook
`
It works

So I don't understand how raspotify call the pidi_spotify hook
